### PR TITLE
Configurable batch_byte_size

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Allows to configure the batch_byte_size parameter, which helps to limit UDP package sizes.

More details: https://github.com/reinh/statsd/pull/65

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Friendly ping @xiejiangzhi, would love some feedback :-)

**Comment by xiejiangzhi** [comment]
@johanneswuerbach 
Thank you very much for your PR.
I'm sorry, because I left the group, I did not get the notice.

**Comment by johanneswuerbach** [comment]
No problem, thank you for making the gem @xiejiangzhi. Would it also be possible to get a new release on rubygems?

**Comment by xiejiangzhi** [comment]
OK, wait a moment.

**Comment by xiejiangzhi** [comment]
@johanneswuerbach 
It's updated.

**Comment by benzheren** [comment]
@xiejiangzhi thanks for updating 😄

**Pull request merged**
